### PR TITLE
Added configurable SameSite cookie setting

### PR DESCRIPTION
**Pull request by Jong-Vincent**
We have added the possibility to configure the SameSite attribute used for the SESSION cookie. Default value have been set to the value previously used in code.

Important note: this does include a breaking change namely the replacement of parameter 'secure_cookie' with 'cookie.secure'.

### CODE REVIEW

**Comment by Jong-Vincent** [comment]
Hi,
It has been a while and I was wondering if there has been any progress regarding this pull request. 
Feel free to let me know if there are any questions.

**Comment by quartje** [comment]
Personally I would say that setting the SameSite Cookie parameter to "none" here is a bad idea, since various browsers will break. 
A list of incompatible clients can be found here: https://www.chromium.org/updates/same-site/incompatible-clients

We have fixed that issue by adding the SameSite cookie attribute in the Haproxy loadbalancer and make exceptions for the incompatible clients. It also allows us to set the attribute for all apps, since many of the apps in the OpenConext ecosystem need the SameSite cookie attribute set to none (because of cross site POSTs during a SAML authentication) 

If you really do need it, I think a switch to disable it completely would be nice, so upstream loadbalancers can add their own.

**Comment by thijskh** [comment]
For manage, can't you assume any user uses a reasonably modern browser and not old chromes or androids?

**Comment by quartje** [comment]
I think you can safely assume that. 

That leaves us still with the fact that this fix would make Manage the only app in our platform to inject SameSite cookie attribute,  So it's fine to add it, as long as we can disable it to make sure it behaves like the other apps.

**Comment by Jong-Vincent** [comment]
From the code snippet below Manage seems to have been setting the SameSite attribute to "None" before as well. 

image

The change that we proposed made this part configurable but have kept the default as "None". Please correct me if I'm wrong but this would then behave the same as before if the default value is kept.

**Comment by quartje** [comment]
I was mistaken! You're absolutely right. I think we should rethink the design of this particular cookie attribute for all apps. This change can be merged of course.

**Pull request merged**
